class TransactionPool:
    def __init__(self):
        self.transaction_map = {}

    def set_transaction(self, transaction):
        """
        Set a transaction in the transaction pool.
        """
        self.transaction_map[transaction.id] = transaction

    def existing_transaction(self, address):
        """
        Find a transaction generated by the address in the transaction pool
        """
        for trans in self.transaction_map.values():
            if trans.input["address"] == address:
                return trans

    def transaction_data(self):
        """
        Return the transactions in the trans pool represented in their JSON form
        """

        transaction_values = self.transaction_map.values()
        transaction_data = list(
            map(lambda transaction: transaction.to_json(), transaction_values)
        )
        return transaction_data

    def clear_blockchain_transactions(self, blockchain):
        """
        Delete blockchain recorded transactions from teh transaction pool.
        """
        for block in blockchain.chain:
            for trans in block.data:
                try:
                    del self.transaction_map[trans["id"]]
                except KeyError:
                    pass
